Repository openwurl/wurlwind, pull requests merged in 2019-09, with the labels that each got.

#1 Finish the initial Configuration functional API and added unit test
  striketracker/client.go
  striketracker/config.go
  striketracker/config_test.go
Labels: Needs Review, enhancement

#2 [WIP] Origin Service
  .travis.yml
  Makefile
  README.md
  main.go
  pkg/integration/client.go
  pkg/integration/integration.go
  pkg/validation/validation.go
  pkg/validation/validators.go
  striketracker/client.go
  striketracker/config.go
  striketracker/models/certificate.go
  striketracker/models/certificate_test.go
  striketracker/models/origin.go
  striketracker/models/response.go
  striketracker/services/authentication/authentication.go
  striketracker/services/certificates/certificates.go
  striketracker/services/certificates/certificates_test.go
  striketracker/services/origin/origin.go
  striketracker/services/origin/origin_test.go
  striketracker/striketracker.go
Labels: Merge Ready, feature

#4 Go Modules
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
  pkg/validation/validation.go
  striketracker/config.go
  vendor/github.com/go-playground/locales/.gitignore
  vendor/github.com/go-playground/locales/LICENSE
  vendor/github.com/go-playground/locales/README.md
  vendor/github.com/go-playground/locales/currency/currency.go
  vendor/github.com/go-playground/locales/logo.png
  vendor/github.com/go-playground/locales/rules.go
  vendor/github.com/go-playground/universal-translator/.gitignore
  vendor/github.com/go-playground/universal-translator/LICENSE
  vendor/github.com/go-playground/universal-translator/README.md
  vendor/github.com/go-playground/universal-translator/errors.go
  vendor/github.com/go-playground/universal-translator/import_export.go
  vendor/github.com/go-playground/universal-translator/logo.png
  vendor/github.com/go-playground/universal-translator/translator.go
  vendor/github.com/go-playground/universal-translator/universal_translator.go
  vendor/github.com/leodido/go-urn/.gitignore
  vendor/github.com/leodido/go-urn/.travis.yml
  vendor/github.com/leodido/go-urn/README.md
  vendor/github.com/leodido/go-urn/machine.go
  vendor/github.com/leodido/go-urn/machine.go.rl
  vendor/github.com/leodido/go-urn/makefile
  vendor/github.com/leodido/go-urn/urn.go
  vendor/github.com/wurlinc/hls-config/pkg/validate/validate.go
  vendor/gopkg.in/go-playground/validator.v9/.gitignore
  vendor/gopkg.in/go-playground/validator.v9/LICENSE
  vendor/gopkg.in/go-playground/validator.v9/Makefile
  vendor/gopkg.in/go-playground/validator.v9/README.md
  vendor/gopkg.in/go-playground/validator.v9/baked_in.go
  vendor/gopkg.in/go-playground/validator.v9/cache.go
  vendor/gopkg.in/go-playground/validator.v9/doc.go
  vendor/gopkg.in/go-playground/validator.v9/errors.go
  vendor/gopkg.in/go-playground/validator.v9/field_level.go
  vendor/gopkg.in/go-playground/validator.v9/logo.png
  vendor/gopkg.in/go-playground/validator.v9/regexes.go
  vendor/gopkg.in/go-playground/validator.v9/struct_level.go
  vendor/gopkg.in/go-playground/validator.v9/translations.go
  vendor/gopkg.in/go-playground/validator.v9/util.go
  vendor/gopkg.in/go-playground/validator.v9/validator.go
  vendor/gopkg.in/go-playground/validator.v9/validator_instance.go
Labels: enhancement
